# Origin in https://github.com/K4R-IAI/iai_donbot_unreal/blob/master/config/costmap_common_params.yaml
#
global_frame: map
robot_base_frame: base_footprint

update_frequency: 5.0
publish_frequency: 5.0

obstacle_range: 5
raytrace_range: 6
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
#robot_radius: ir_of_robot
transform_tolerance: 0.5

inflation:
  inflation_radius: 0.6

obstacles_laser:
  observation_sources: base_scan
  base_scan: {sensor_frame: base_laser_link, topic: /base_scan, data_type: LaserScan, expected_update_rate: 3.0,
             observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
