# Origin in https://github.com/K4R-IAI/iai_donbot_unreal/blob/master/config/costmap_local_params.yaml
#
local_costmap:
  global_frame: odom_combined
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true #was false by default?
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.02
  


  plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}


